# CastleSiege plugin configuration

# PREGAME lobby location
x: 0
y: 64
z: 0

# PREGAME countdown delay in seconds
pregameDelay: 10

#World players need to be in to participate in game
gameWorld: world

#Minimum amount of players needed for a game (needs to be at least 2)
minPlayerAmount: 4
